# The JSONPath filter expression used to identify which PRs to close.
# The data filtered is the pull request data along with other metadata passed in
# by probot.
# See http://linkremoved/
# `true` will close all PRs.
filters:
  - true

# The message to post to the closed PR.
commentBody: |
  for any contributions email me at MrRawes@protonmail.com with title firefox-hosts

# Whether to add a label to the closed PR.
addLabel: false
